import SwiftUI

// MARK: - 中英文案表（由 scripts/localize.py 从 i18n/*.tsv 生成，勿手改）

extension L10n {

    /// 中文原文（含 {0} 占位符）→ 英文
    static let enTable: [String: String] = [
        "16 色": "16 Colors",
        "24 色": "24 Colors",
        "295 色": "295 Colors",
        "295 色（全色板）": "295 Colors (Full)",
        "32 色": "32 Colors",
        "48 色": "48 Colors",
        "52 钉 ≈ 14cm、78 钉 ≈ 21cm、104 钉 ≈ 28cm。新建手绘、拆板与尺寸分离以此作为默认板尺寸；灯板发图尺寸始终按图纸本身。": "52 pins ≈ 14cm, 78 pins ≈ 21cm, 104 pins ≈ 28cm. Used as the default board size for drawings, splitting, and placement; images are always sent at the pattern's own size.",
        "64 色": "64 Colors",
        "<无名 {0}>": "<Unnamed {0}>",
        "A951 指令": "A951 Command",
        "A951(指令)": "A951 (Command)",
        "A952 数据": "A952 Data",
        "A952(数据)": "A952 (Data)",
        "A953(通知，可选)": "A953 (Notify, optional)",
        "Connect 无应答": "Connect: no response",
        "PDF 已生成，可点「分享 PDF」导出": "PDF ready — tap \"Share PDF\" to export",
        "PDF 生成失败，请重试": "PDF generation failed, try again",
        "TestPass 无应答": "TestPass: no response",
        "{0}  需{1} 有{2} 缺{3}": "{0}  need {1} have {2} short {3}",
        "{0} / {1} 颗": "{0} / {1} beads",
        "{0} / {1} 颗 · {2}%": "{0} / {1} beads · {2}%",
        "{0} · 作品卡": "{0} · Share Card",
        "{0} × {1} = {2} 块": "{0} × {1} = {2} tiles",
        "{0} × {1} 格": "{0} × {1} cells",
        "{0} × {1} 格 · 约 {2} 颗": "{0} × {1} cells · about {2} beads",
        "{0} 个": "{0} items",
        "{0} 个色号 · {1} 颗": "{0} colors · {1} beads",
        "{0} 图纸 {1}": "{0} Patterns {1}",
        "{0} 张图纸": "{0} patterns",
        "{0} 格": "{0} cells",
        "{0} 格空白": "{0} cells gap",
        "{0} 种": "{0} colors",
        "{0} 种颜色": "{0} colors",
        "{0} 色": "{0} colors",
        "{0} 行": "{0} rows",
        "{0} 颗": "{0} beads",
        "{0}/{1} 块已完成": "{0}/{1} tiles done",
        "{0}s 内未发现必需特征（缺 {1}）。已发现的特征：[{2}]。这可能不是拼豆板，或固件使用了不同的特征 UUID": "No required characteristics within {0}s (missing {1}). Found: [{2}]. This may not be a bead board, or the firmware uses different UUIDs",
        "{0}×{1} · {2} 色 · {3} 颗": "{0}×{1} · {2} colors · {3} beads",
        "{0}×{1} · {2} 颗": "{0}×{1} · {2} beads",
        "{0}×{1} · {2}颗": "{0}×{1} · {2} beads",
        "{0}×{1} 格": "{0}×{1} cells",
        "{0}×{1} 格 · 约 {2}cm": "{0}×{1} cells · about {2}cm",
        "…等共 {0} 色，保存后可在图纸详情查看完整清单": "…{0} colors total; see the full list in pattern details",
        "≤ 16 色": "≤ 16 Colors",
        "≤ 24 色": "≤ 24 Colors",
        "≤ 48 色": "≤ 48 Colors",
        "「{0}」中的库存会移动到「{1}」，记录不会删除。": "Stock in {0} moves to {1}; records are not deleted.",
        "「{0}」及其进度将被永久删除": "{0} and its progress will be deleted permanently",
        "「{0}」的 {1} 条库存已归回默认仓": "{1} entries of {0} moved to Default Bin",
        "「{0}」还没有库存，点右上角「+」添加或批量导入": "{0} has no stock — tap + to add or import",
        "「原图缓存」仅指照片转图纸时保留的原图；清除后图纸本身与进度不受影响。临时导出文件指应用临时目录下的 PDF 导出件。": "Photo cache only refers to original photos kept for conversions; clearing it does not affect patterns or progress. Temp exports are PDFs in the app temp folder.",
        "【{0}】库存充足，无缺色 🎉": "[{0}] Stock sufficient, nothing short 🎉",
        "【{0}】缺色清单": "[{0}] Shortage List",
        "【{0}】豆子清单": "[{0}] Bead List",
        "【豆绘小栈】补豆清单（全部图纸汇总）": "[DouPin] Restock List (all patterns)",
        "一种颜色一次买齐、一次拼完时，用右侧按钮整色打卡。": "When finishing a color at once, mark the whole color with the button.",
        "一键复制缺色清单": "Copy Shortage List",
        "一键生成像素图": "One-tap Pixel Art",
        "下接 R{0}C{1}": "Below: R{0}C{1}",
        "下载中…": "Downloading…",
        "主题": "Theme",
        "云朵": "Cloud",
        "五角星": "Star",
        "亮度": "Brightness",
        "仅 {0}": "{0} only",
        "仅 {0}（{1} 颗）": "{0} only ({1} beads)",
        "仅「照片转图纸」来源的图纸支持原图对比。": "Only photo-based patterns support comparison.",
        "仅使用库存中数量大于 0 的色号——转图与选色只会用到你手上有的颜色，避免配不到色。": "Uses only colors with stock > 0, so conversions and picks stay within what you own.",
        "仅保存图纸": "Save Only",
        "仅库存": "Stock Only",
        "仅我的库存色": "My Stock Only",
        "仅按图纸用量一次性扣减已存在的色号；不记录出入库流水，扣减后可在库存页手动修正。": "Deducts existing colors by usage once; no ledger is kept — adjust stock manually if needed.",
        "仅显示 Mard {0}": "Mard {0} only",
        "从 295 色板中挑选": "Pick from 295 colors",
        "从剪贴板粘贴": "Paste from Clipboard",
        "从小红书链接导入": "Import from RedNote Link",
        "从模板开始": "Start from Template",
        "从相册导入": "Import from Photos",
        "仓名，如「Mard 主仓」": "Bin name, e.g. Mard Main",
        "仓名，如「漫漫 补充仓」": "Bin name, e.g. Manman Backup",
        "仙人掌": "Cactus",
        "低于阈值 {0}": "Below threshold {0}",
        "作品": "Works",
        "作品分享卡": "Share Card",
        "作品集": "Gallery",
        "使用此模板开始拼": "Start with This Template",
        "使用颜色": "Colors Used",
        "例如 500": "e.g. 500",
        "保存": "Save",
        "保存为图纸": "Save as Pattern",
        "保存全部子图（{0} 块）": "Save all tiles ({0})",
        "保存图纸": "Save Pattern",
        "保存失败": "Save Failed",
        "保存失败：{0}": "Save failed: {0}",
        "保存并开始拼豆（发送拼豆板）": "Save & Start (Send to Board)",
        "信息": "Info",
        "修改已保存": "Edit Saved",
        "像素图": "Pixel Art",
        "像素小动物": "Pixel Animals",
        "像素数据长度不符": "Pixel Data Size Mismatch",
        "充足": "Enough",
        "先到「库存」标签录入色号数量，再回来查看这张图纸的缺色情况。": "Add stock quantities first, then check shortages here.",
        "兔子": "Bunny",
        "全拼完": "Mark All",
        "全显": "Show All",
        "全部": "All",
        "全部图纸": "All Patterns",
        "全部标签": "All Tags",
        "全部（295 色）": "All (295 Colors)",
        "共 {0} 张候选图片，请选择一张：": "{0} candidate images — pick one:",
        "共 {0} 张图纸": "{0} patterns total",
        "共 {0} 种色号不足": "{0} colors short",
        "共 {0} 种色号，缺 {1} 颗": "{0} colors · {1} beads short",
        "共 {0} 种颜色，{1} 颗": "{0} colors, {1} beads",
        "共 {0} 色": "{0} colors total",
        "关于": "About",
        "关闭": "Close",
        "内置图纸模板，直接开拼": "Built-in templates, start right away",
        "写入特征": "Write Characteristic",
        "冰淇淋": "Ice Cream",
        "冲突处理": "On Conflict",
        "冲突时": "On Conflict",
        "准备握手…": "Preparing…",
        "分 {0} 个豆仓管理 · 图纸详情可查看消耗预估": "Managed in {0} bins · see estimate in pattern details",
        "分享 / 存储": "Share / Save",
        "分享 PDF（{0}.pdf）": "Share PDF ({0}.pdf)",
        "分享作品卡": "Share Card",
        "分色引导 · 全图点亮": "Color Guide · Whole Pattern",
        "分色打卡": "By Color",
        "分色点亮：只亮选中色号；「此色拼完」会自动打卡整色并点亮下一色。": "Color guide: only the selected color lights up; finishing it marks and lights the next.",
        "创作总览": "Overview",
        "创建": "Create",
        "删除": "Delete",
        "删除作品": "Delete Work",
        "删除作品？": "Delete Work?",
        "删除文件夹？": "Delete Folder?",
        "删除自定义仓时，其中的库存会归回默认仓，不会丢数据。": "Dissolving a bin returns its stock to Default Bin — no data lost.",
        "删除该色号库存": "Delete This Stock",
        "删除该色号库存？": "Delete This Stock?",
        "剩{0}": "{0} left",
        "剩余": "Left",
        "十六进制帧，如 54 0d 00 02 00 57": "Hex frame, e.g. 54 0d 00 02 00 57",
        "南瓜": "Pumpkin",
        "原图": "Original",
        "原图对比": "Compare",
        "原图缓存占用": "Original Photo Cache",
        "原色": "True Color",
        "原色号（要替换掉的）": "Source Color (Replace)",
        "去录入库存": "Add Stock",
        "双心": "Twin Hearts",
        "发现新版本（远端 {0}）——点上方仓库链接下载最新 IPA": "Update available (remote {0}) — download the latest IPA from the repo link",
        "发现服务失败：{0}": "Service discovery failed: {0}",
        "发送": "Send",
        "发送失败：{0}": "Send failed: {0}",
        "发送完整图，开始拼豆": "Send Full Image and Start",
        "发送完整预览图": "Send Full Preview",
        "发送模式": "Send Mode",
        "取消": "Cancel",
        "取消分色": "Clear Color",
        "受影响格数": "Affected Cells",
        "叠加半透明": "Semi-transparent",
        "叠加对比": "Overlay",
        "只列出不够的色号及缺口，可复制后发给卖家补豆。": "Lists only short colors; copy and send to your supplier.",
        "只点亮选中色号在全图中的位置。逐颗拼完可到「进度」打卡；整色拼完点「此色拼完」自动打卡并点亮下一色（未拼颗数多的优先）。": "Lights only the selected color across the pattern. Mark cells in Progress, or use Color Done to finish a color and light the next.",
        "可以先「逐条添加」几个常用色号，或把一段「色号 数量」文本「批量导入」。豆子多的话，还能按品牌/用途建多个豆仓分区管理。": "Add colors one by one or import a list of \"code quantity\" lines. You can also split beads into multiple bins by brand or purpose.",
        "可发送": "Ready",
        "可用于匹配": "Available for Matching",
        "右接 R{0}C{1}": "Right: R{0}C{1}",
        "合并图纸": "Merge",
        "合并图纸名称": "Merged Pattern Name",
        "合并图纸（多图拼一张）": "Merge (Several into One)",
        "合并明细（{0} 项）": "Merge details ({0})",
        "合并相近色": "Merge Similar Colors",
        "名称": "Name",
        "向日葵": "Sunflower",
        "吸管": "Eyedropper",
        "咖啡杯": "Coffee Cup",
        "咖啡杯日常": "Coffee Daily",
        "哭泣": "Crying",
        "图例": "Legend",
        "图片下载失败，请检查网络后重试（可直接再次点击该图片）。": "Download failed; check network and tap the image again.",
        "图纸": "Patterns",
        "图纸 {0}×{1} 落在 {2}×{3} 板上，空白区视为空格（不点灯）。": "Pattern {0}×{1} on a {2}×{3} board; blank areas stay empty (no lights).",
        "图纸 · 拼豆模式": "Pattern · Bead Mode",
        "图纸不超过一块板（{0}×{1}），无需拆分。": "Pattern fits one board ({0}×{1}); no split needed.",
        "图纸名称": "Pattern Name",
        "图纸尺寸": "Pattern Size",
        "图纸尺寸或板尺寸不合法（需 > 0）。": "Invalid pattern or board size (must be > 0).",
        "图纸已保存，可在「图纸」标签中查看": "Saved; view it in the Patterns tab",
        "图纸间隔": "Gap",
        "土星": "Saturn",
        "圣诞树": "Christmas Tree",
        "圣诞袜": "Christmas Stocking",
        "在图纸详情里「编辑标签」，即可按标签归档": "Use \"Edit Tags\" in pattern details to organize by tag",
        "垂直偏移": "Offset Y",
        "填充": "Fill",
        "复位": "Reset",
        "复位缩放": "Reset Zoom",
        "复制清单": "Copy List",
        "复制豆子清单": "Copy Bead List",
        "外观与反馈": "Appearance",
        "多图拼一张大图": "Merge Several into One",
        "多图拼一张大图（PIXDOU 同款排版）": "Merge several into one (PIXDOU-style layout)",
        "大笑": "Laughing",
        "太空星球": "Planet",
        "太阳": "Sun",
        "好": "OK",
        "子块（{0} 块）": "Tiles ({0})",
        "字母 A": "Letter A",
        "字母 K": "Letter K",
        "字母数字": "Alphanumeric",
        "存储": "Storage",
        "完成": "Done",
        "完成于 {0}": "Completed {0}",
        "完整预览：已拼的格子以暗色显示。": "Full preview: placed cells are dimmed.",
        "实时预览": "Live Preview",
        "宽 {0} × 高 {1} 格 · 共 {2} 颗 · 豆绘小栈": "W {0} × H {1} cells · {2} beads · DouPin",
        "导入完成": "Import Finished",
        "导入完成：新增 {0} / 更新 {1} / 跳过 {2} / 失败 {3}": "Import done: {0} new / {1} updated / {2} skipped / {3} failed",
        "导出 PDF": "Export PDF",
        "导出图纸图片": "Export Image",
        "寿司": "Sushi",
        "将删除应用临时目录下的 PDF 导出文件（不影响已保存到「文件」的副本）。": "Deletes PDFs in the app temp folder (copies saved to Files are kept).",
        "将删除所有图纸保留的原图缓存（{0}）。图纸本身、色号与进度都会保留。此操作不可撤销。": "Deletes cached original photos ({0}). Patterns, colors, and progress are kept. This cannot be undone.",
        "将移除 {0} 的库存记录": "Remove stock record for {0}",
        "小企鹅": "Penguin",
        "小牛": "Calf",
        "小狐狸": "Fox",
        "小狗": "Puppy",
        "小猫": "Kitten",
        "小红书图纸 {0}": "RedNote Pattern {0}",
        "小鸡": "Chick",
        "尺寸": "Size",
        "尺寸（最大边格数）": "Size (Max Side)",
        "居中": "Center",
        "属于「{0}」的第 {1} 块": "Tile {1} of {0}",
        "山峰": "Mountain",
        "工具": "Tools",
        "左上角": "Top Left",
        "差额 = 现有 − 需要；负数（不够）标红，正数（富余）标绿。": "Diff = have − need; negative is red, positive is green.",
        "已保存": "Saved",
        "已保存 {0} 块子图，可在「图纸」中逐块查看与打卡。": "Saved {0} tiles; view and mark them in Patterns.",
        "已切到「{0}」": "Switched to {0}",
        "已切到新仓「{0}」，录入的豆子会归入此仓": "Switched to bin {0}; new stock goes here",
        "已删除 {0}": "Deleted {0}",
        "已存在": "Exists",
        "已完成": "Completed",
        "已完成！{0}": "Completed! {0}",
        "已录入色号": "Colors Logged",
        "已拼": "Placed",
        "已按用量扣减 {0} 个色号": "Deducted {0} colors by usage",
        "已握手，可以发图和点亮引导": "Handshaked, ready to send and guide",
        "已新增 {0}": "Added {0}",
        "已新建并切到「{0}」": "Created and switched to {0}",
        "已是最新版本（{0}）": "Up to date ({0})",
        "已更新 {0}": "Updated {0}",
        "已清理 {0} 个临时导出文件": "Cleaned {0} temp export files",
        "已清除 {0} 张原图缓存": "Cleared {0} cached photos",
        "已生成合并图纸": "Merged Pattern Created",
        "已连接": "Connected",
        "已连接 {0}": "Connected to {0}",
        "已连接，正在握手…": "Connected, handshaking…",
        "已选 {0}/9": "{0}/9 selected",
        "已重命名为「{0}」": "Renamed to {0}",
        "常用指令（含校验，可直接粘贴）：握手 Connect = 54 0d 00 03 00 00 64；校验密码 TestPass = 54 0f 00 08 00 00 00 00 00 00 00 6b；亮度 5 级 = 54 09 00 0b 05 00 00 00 00 00 00 00 00 00 6d；开屏 = 54 0a 00 0b 01 00 00 00 00 00 00 00 00 00 70。用于协议排查。": "Common commands (checksums included, paste as-is): Connect = 54 0d 00 03 00 00 64; TestPass = 54 0f 00 08 00 00 00 00 00 00 00 6b; brightness 5 = 54 09 00 0b 05 00 00 00 00 00 00 00 00 00 6d; display on = 54 0a 00 0b 01 00 00 00 00 00 00 00 00 00 70. For protocol debugging.",
        "库存": "Stock",
        "库存充足，图纸详情可查看消耗预估": "Stock is sufficient; see estimate in pattern details",
        "库存充足，无缺色 🎉": "Stock is sufficient 🎉",
        "库存充足，暂时不需要补豆": "Stock is sufficient, nothing to restock",
        "库存总豆量": "Total Stock",
        "库存色系分布": "Stock by Color Family",
        "库存还是空的": "Stock Is Empty",
        "应用": "Apply",
        "应用名": "App Name",
        "开启自动连接后，点任意页面右上角的「连接」会直接搜索并连上 PIXDOU 板子；关闭后改为弹出面板手动选择。亮度与相邻行微亮用于行/分色引导。": "With auto-connect on, tapping Connect searches and connects to a PIXDOU board directly; when off you pick a device manually. Brightness and neighbor dimming apply to row/color guides.",
        "开始拼豆": "Start Beading",
        "开始拼豆（发送拼豆板）": "Start Beading (Send to Board)",
        "开始转换": "Convert",
        "引导时微亮相邻行": "Dim Neighbor Rows",
        "归入豆仓": "Into Bin",
        "当前": "Current",
        "当前档位：{0}（可在「设置 → 颜色」调整）": "Tier: {0} (adjust in Settings → Colors)",
        "当前版本": "Version",
        "当前行引导": "Current Row Guide",
        "当前豆仓 · {0}": "Current bin · {0}",
        "当前阈值下无相近色可合并。": "No similar colors to merge at this threshold.",
        "当前默认板": "Default Board",
        "当导入的色号已有库存时：累加 = 原数量 + 导入数量；覆盖 = 直接改为导入数量；跳过 = 保留原库存。": "If a color already exists: Add = sum, Overwrite = replace, Skip = keep current.",
        "彩虹": "Rainbow",
        "待拼": "To Do",
        "快捷控制": "Quick Controls",
        "总数": "Total",
        "总豆量": "Total Beads",
        "总进度": "Overall Progress",
        "总需豆量": "Total Needed",
        "总颗数": "Total Beads",
        "成功 {0} · 失败 {1}": "OK {0} · Failed {1}",
        "成品": "Finished",
        "成品归档 · 作品分享卡": "Works archive · Share card",
        "成品照": "Photo",
        "成品照片": "Finished Photo",
        "我的": "Me",
        "我的作品集": "My Gallery",
        "我的图纸": "My Patterns",
        "我的豆仓": "My Bin",
        "所有已拼标记将被清除": "All placement marks will be cleared",
        "手动发送指令": "Manual Command",
        "手动设置边长": "Set Side Manually",
        "手绘画布": "Draw Canvas",
        "打卡 + 前进": "Mark & Next",
        "打卡模式": "Mark Mode",
        "打开小红书笔记 →「分享」→「复制链接」，粘贴到这里即可。\\n仅抓取公开分享页图片，供个人自用参考，请尊重原作者版权。": "Open the RedNote note → Share → Copy Link, then paste it here.\\nOnly public share-page images are fetched, for personal reference only — please respect the author's copyright.",
        "打开项目仓库（下载最新 IPA）": "Open project repo (download latest IPA)",
        "扫描中…": "Scanning…",
        "批量导入": "Bulk Import",
        "找不到板子时打开，查看是否被名称过滤挡掉": "Turn on if your board is missing, to bypass name filter",
        "抓取失败（可能网络超时或分享页受限）。可改用「从相册选择图片」。": "Fetch failed. Try \"Choose from Photos\".",
        "拆板": "Split",
        "拆板设置": "Split Settings",
        "拼制中": "In Progress",
        "拼完一张图纸并打卡完成后，会自动出现在这里；上传成品照片还能生成作品卡分享。": "Finished patterns appear here; add a photo to create a share card.",
        "拼完一行点一下；点错了再点一次即可撤销该行。": "Tap once per finished row; tap again to undo.",
        "拼完当前行后点击，会自动标记该行已拼并点亮下一行。": "Marks the row placed and lights the next row.",
        "拼接方式": "Layout",
        "拼板布局": "Board Layout",
        "拼豆板": "Bead Board",
        "拼豆板已连接": "Board Connected",
        "拼豆板未连接": "Board Not Connected",
        "拼豆板规格": "Board Model",
        "按品牌或用途分区后，各仓的色号与豆量独立管理与统计；补豆清单仍按全部豆仓汇总。": "Bins are managed and counted separately; the restock list still sums all bins.",
        "按品牌或用途给豆子分区，各仓独立管理与统计。": "Split beads by brand or purpose; each bin is managed separately.",
        "按本图纸用量扣减库存（便利）": "Deduct stock by this pattern's usage",
        "按色号搜索（Mard/可可/漫漫…）": "Search by color code (Mard/Coco/Manman…)",
        "按颜色过滤当前行…": "Filter Current Row by Color…",
        "换个筛选条件看看。": "Try another filter.",
        "接缝": "Seam",
        "提示：在 App 中把感兴趣的内容截图或保存图片，再走相册导入即可。": "Tip: screenshot or save the image in the app, then import from Photos.",
        "握手失败：{0}": "Handshake failed: {0}",
        "搜索中": "Searching",
        "搜索图纸名称": "Search Pattern Name",
        "搜索色号（Mard/可可/漫漫…）": "Search color code (Mard/Coco/Manman…)",
        "改用「从相册选择图片」": "Use \"Choose from Photos\"",
        "放大网格后格内会显示 Mard 色号；「白色」模式去掉颜色只看形状，适合确认轮廓。": "Zoom in to see Mard codes in cells; White mode shows shapes only.",
        "数字 0": "Digit 0",
        "数字 8": "Digit 8",
        "数据中心": "Data Center",
        "数量": "Quantity",
        "数量（覆盖）": "Quantity (Overwrite)",
        "文件夹": "Folders",
        "文件夹内的图纸不会被删除，将被移出到「全部」。": "Patterns inside are kept and moved to All.",
        "文件夹名称": "Folder Name",
        "文件夹是空的": "Folder Is Empty",
        "断开连接": "Disconnect",
        "新增 {0} 条 · 更新 {1} 条 · 跳过 {2} 条 · 失败 {3} 行": "{0} new · {1} updated · {2} skipped · {3} failed",
        "新增标签": "Add Tag",
        "新年灯笼": "Lantern",
        "新建仓": "New Bin",
        "新建手绘": "New Drawing",
        "新建手绘（导入后手动归入）": "New Drawing (assign later)",
        "新建文件夹": "New Folder",
        "新建豆仓": "New Bin",
        "新的仓名": "New Bin Name",
        "新色号（替换为）": "New Color (Replace With)",
        "无法初始化数据库：{0}": "Cannot initialize database: {0}",
        "无法拆板": "Cannot Split",
        "无法解析十六进制字节": "Cannot parse hex bytes",
        "无法识别": "Unrecognized",
        "无法识别：数量「{0}」不是整数": "Invalid quantity: {0}",
        "无法识别：色号「{0}」不在 295 色板中": "Unknown color code {0} (not in the 295 palette)",
        "无法识别：需要「色号 数量」两个字段": "Unrecognized: need \"code quantity\"",
        "无语": "Speechless",
        "无需拆分": "No Split Needed",
        "日常物件": "Daily Objects",
        "日志（最新在前）": "Log (Newest First)",
        "明细": "Details",
        "星星点点": "Sparkles",
        "显示全部蓝牙设备": "Show All BLE Devices",
        "更换成品照片": "Change Photo",
        "更新": "Update",
        "替换为空（清空该色）": "Replace with Empty",
        "替换配色": "Replace Colors",
        "最近完成": "Recently Completed",
        "月亮": "Moon",
        "月牙星": "Crescent Star",
        "未命名": "Untitled",
        "未命名作品": "Untitled Work",
        "未成功提取": "Extraction Failed",
        "未拆板": "Not Split",
        "未生成任何子图，请检查图纸数据。": "No tiles generated; check pattern data.",
        "未知": "Unknown",
        "未知设备": "Unknown Device",
        "未能从分享页解析到图片。可改用「从相册选择图片」。": "No image found on the page. Try \"Choose from Photos\".",
        "未识别到链接，请重新复制小红书分享文案后再试。": "No link found; copy the RedNote share text again.",
        "未连接": "Not Connected",
        "本地优先 · 无账户 · 数据只存在你的设备上": "Local-first · No account · Data stays on your device",
        "本月完成": "This Month",
        "本次已添加 {0} 条": "Added {0} entries this session",
        "本行已拼完": "Row Completed",
        "本行拼完 → 下一行": "Row Done → Next Row",
        "板子亮度": "Board Brightness",
        "板子未连接": "Board Not Connected",
        "板子设置了密码，请先用官方 app 清除密码": "Board is password-protected; clear it with the official app first",
        "板宽": "Board W",
        "板尺寸 {0}×{1} · 本页 行{2}-{3} 列{4}-{5}": "Board {0}×{1} · this page rows {2}-{3}, cols {4}-{5}",
        "板尺寸预设": "Board Presets",
        "板规格": "Board Model",
        "板规格 · 色板档位 · 语言 · 更新": "Board · Palette tier · Language · Updates",
        "板高": "Board H",
        "构建": "Build",
        "构建号来自云端构建注入的提交短 SHA；与仓库最新提交一致即为最新版。": "Build ID is the commit SHA injected by CI; same as the repo head means up to date.",
        "构建时间": "Built At",
        "枫叶": "Maple Leaf",
        "查看": "View",
        "查重与写入都在该豆仓内进行；同色号在其他仓的记录不受影响。": "Lookups and writes happen inside this bin only.",
        "标签": "Tags",
        "标签「{0}」": "Tag {0}",
        "标签用于「图纸 → 标签」分段筛选。": "Tags filter patterns under Patterns → Tags.",
        "档位按 Mard 色号顺序取前 N 色，与出厂套装一致；若与你的实物色卡不符，请选「仅我的库存色」，或在库存页录入你实际拥有的色号。": "Tiers take the first N Mard codes in order, matching factory sets. If your card differs, choose \"My Stock Only\" or log the colors you own.",
        "检查失败：{0}": "Check failed: {0}",
        "检测更新": "Check for Updates",
        "棒棒糖": "Lollipop",
        "植物花语": "Plants",
        "模式": "Mode",
        "模板库": "Templates",
        "樱花": "Cherry Blossom",
        "橡皮": "Eraser",
        "正在发送… {0}%": "Sending… {0}%",
        "正在发送引导图… {0}%": "Sending guide… {0}%",
        "正在搜索 PIXDOU…（点此取消）": "Searching PIXDOU… (tap to cancel)",
        "正在搜索拼豆板…": "Searching for Bead Board…",
        "正在检查…": "Checking…",
        "此色拼完 → 下一色": "Color Done → Next Color",
        "每块子图独立保存为图纸，可逐块上板拼、逐块打卡。": "Each tile is saved as a pattern you can bead and mark separately.",
        "每行：色号 数量\\n例如：\\nA1 500\\nA2,300\\nH7\\t120": "One per line: code quantity\\nFor example://nA1 500\\nA2,300\\nH7\\t120",
        "水平偏移": "Offset X",
        "汇总": "Summary",
        "没找到 PIXDOU 拼豆板。请确认板子已通电、蓝牙已开启，或手动选择设备。": "No PIXDOU board found. Make sure it is powered on with Bluetooth enabled, or pick a device manually.",
        "没有匹配的色号": "No Matching Color",
        "没有发现临时导出文件": "No temp export files found",
        "没有可清除的原图缓存": "No original photos to clear",
        "没有含「{0}」的图纸": "No patterns tagged {0}",
        "没有符合筛选的图纸": "No Patterns Match the Filter",
        "没有需要更新的记录": "Nothing to Update",
        "浅色": "Light",
        "海浪": "Wave",
        "消耗排行": "Usage Ranking",
        "消耗排行 · 补豆清单 · 色系分布": "Usage ranking · Restock list · Color families",
        "消耗预估": "Estimate",
        "深色": "Dark",
        "添加": "Add",
        "添加成品照片": "Add Finished Photo",
        "清理": "Clean Up",
        "清理临时导出文件": "Clean Temp Exports",
        "清理临时导出文件？": "Clean Temp Exports?",
        "清空": "Clear",
        "清空拼制进度": "Reset Progress",
        "清空拼制进度？": "Reset Progress?",
        "清除": "Remove",
        "清除全部原图": "Clear All Photos",
        "清除全部原图？": "Clear All Photos?",
        "火箭": "Rocket",
        "点「自动连接拼豆板」会自动搜索并连接名字带 PIXDOU 的板子（也兼容 iLEDColor / Wofan）；没连上时可在下方列表手动选择。": "Auto-connect searches for boards named PIXDOU (also iLEDColor / Wofan); if it fails, pick one from the list below.",
        "点下方按钮搜索附近的拼豆板": "Tap below to search for your board",
        "点亮当前行（含相邻行微亮）": "Light current row (neighbors dimmed)",
        "点亮灯板": "Turn On Board",
        "点亮该色": "Light This Color",
        "点亮该色，开始拼豆": "Light This Color and Start",
        "点击下方色块高亮显示；再点一次或点「全显」恢复。": "Tap a swatch below to highlight; tap again or Show All to reset.",
        "点击选择照片": "Tap to Choose Photo",
        "点击选择色号": "Tap to Choose Color",
        "点右上角「+」导入图纸，将自动归入「{0}」": "Tap + to import; patterns go to {0}",
        "点右上角「连接」按钮连上拼豆板后，可以在这里点亮当前行辅助定位。": "Connect the board first, then light the current row here.",
        "点右上角「连接」按钮连上拼豆板后，这里就能发送": "Connect the board via the top-right button, then send here",
        "照片变图纸 · 图纸点亮拼豆板": "Photos to patterns, patterns to lights",
        "照片变图纸，图纸点亮拼豆板": "Photos to patterns, patterns to light",
        "照片图纸 {0}": "Photo Pattern {0}",
        "照片转图纸": "Photo to Pattern",
        "熊猫": "Panda",
        "爱心": "Heart",
        "爱心眼": "Heart Eyes",
        "爱心系": "Hearts",
        "版本": "Version",
        "版本 1.2 · 本地优先 · 无账户": "Version 1.2 · Local-first · No account",
        "状态": "Status",
        "现有标签": "Existing Tags",
        "甜甜圈": "Donut",
        "生成作品分享卡": "Create Share Card",
        "生成合并图纸": "Generate Merged Pattern",
        "生日蛋糕": "Birthday Cake",
        "用文件夹给图纸归档，找图更快": "Use folders to organize patterns",
        "用时约 {0} 天": "About {0} days",
        "用照片转换、手绘或模板创建第一张图纸": "Create your first pattern from a photo, drawing, or template",
        "用色数": "Colors Used",
        "用色清单": "Color List",
        "画笔": "Brush",
        "疑似拼豆板": "Likely Bead Board",
        "白底转空格": "White to Empty",
        "白色": "White",
        "相似度阈值": "Similarity Threshold",
        "确定": "Confirm",
        "确认导入": "Confirm Import",
        "碎花爱心": "Floral Heart",
        "礼物盒": "Gift Box",
        "移出文件夹": "Remove from Folder",
        "移动到文件夹": "Move to Folder",
        "移除成品照片": "Remove Photo",
        "竖版长图：成品照（或图纸）+ 尺寸豆量 + 色号用量 Top6，可直接发微信/小红书。": "Portrait card: photo (or pattern) + size and bead count + top 6 colors — ready to share.",
        "笑脸": "Smiley",
        "第 {0} / {1} 行": "Row {0} / {1}",
        "第 {0} 行：{1}": "Line {0}: {1}",
        "第 {0}/{1} 页": "Page {0}/{1}",
        "第{0}行": "Row {0}",
        "筛选": "Filter",
        "简体中文": "简体中文",
        "管理": "Manage",
        "管理豆仓": "Manage Bins",
        "粉色爱心": "Pink Heart",
        "粘贴小红书分享链接 / 文案": "Paste RedNote share link / text",
        "粘贴文本": "Paste Text",
        "粘贴文本后将在此处显示解析预览": "Parsing preview appears here after pasting",
        "系统连接失败：{0}": "Connection failed: {0}",
        "累计颗数": "Total Beads",
        "纸杯蛋糕": "Cupcake",
        "统计": "Stats",
        "编号": "No.",
        "编辑": "Edit",
        "编辑图纸": "Edit Pattern",
        "编辑库存": "Edit Stock",
        "编辑标签": "Edit Tags",
        "缺 {0}": "Short {0}",
        "缺 {0} 种色号 · 共 {1} 颗（按全部图纸需求汇总）": "{0} colors short · {1} beads needed (summed over all patterns)",
        "缺 {0} 种色号 · 共 {1} 颗，点看补豆清单": "{0} colors short · {1} beads needed; tap for the list",
        "缺色": "Out of Stock",
        "缺色 ⚠︎": "Short ⚠︎",
        "缺色清单": "Shortage List",
        "缺色清单已复制": "Shortage List Copied",
        "缺色种数": "Shortage Colors",
        "缺色（库存为 0）": "Out of Stock (0)",
        "自动亮度校正": "Auto Levels",
        "自动匹配 295 色豆号，亮度和色彩智能校正": "Matches all 295 bead colors with smart level and color correction",
        "自动连接拼豆板": "Auto-connect Board",
        "自定义": "Custom",
        "自定义板尺寸": "Custom Board Size",
        "自定义豆仓（{0}）": "Custom bins ({0})",
        "自然风景": "Landscape",
        "自由绘制创作": "Draw Freely",
        "色号": "Color No.",
        "色号 · 需要 · 现有 · 差额": "Color · Need · Have · Diff",
        "色号统计（共 {0} 种颜色）": "Color stats ({0} colors)",
        "色板 · {0}": "Palette · {0}",
        "色板 · {0} 色": "Palette · {0} colors",
        "色板档位": "Palette Tier",
        "节日": "Holiday",
        "英文界面正在逐步补齐（当前覆盖标签栏、设置页与首页主文案）。": "English UI is being completed (currently tabs, settings, and home).",
        "草莓": "Strawberry",
        "蓝牙控制台": "BLE Console",
        "蓝牙日志控制台": "BLE Log Console",
        "蓝牙未开启": "Bluetooth Off",
        "蘑菇": "Mushroom",
        "虚线为板边界，每块左上角为编号（R行C列）。": "Dashed lines mark board edges; each tile is labeled R-row C-col.",
        "蝴蝶结": "Ribbon",
        "补豆清单": "Restock List",
        "补豆清单已复制": "Restock List Copied",
        "表情包": "Emoji",
        "西瓜": "Watermelon",
        "解散": "Dissolve",
        "解散该豆仓？": "Dissolve This Bin?",
        "解散，库存归回默认仓": "Dissolve, stock returns to Default Bin",
        "解析中…": "Parsing…",
        "解析链接": "Parse Link",
        "解析预览": "Parse Preview",
        "触觉反馈": "Haptics",
        "设置": "Settings",
        "设置实际拼板尺寸": "Set Physical Board Size",
        "该仓没有库存记录": "No Stock in This Bin",
        "该图纸无原图": "No Original Photo",
        "该筛选下没有作品": "No Works in This Filter",
        "该色号在本仓已有 {0} 颗（保存将累加）": "Already {0} in this bin (values add up)",
        "该补豆啦": "Restock Time",
        "该设备没有暴露任何 GATT 服务（可能不是拼豆板，或已被官方 App 占用）": "This device exposes no GATT services (not a bead board, or used by the official app)",
        "语言": "Language",
        "请在系统设置中打开蓝牙": "Turn on Bluetooth in Settings",
        "请确保拼豆板已通电": "Make sure the board is powered on",
        "豆仓管理": "Manage Bins",
        "豆子": "Beads",
        "豆子总数": "Total Beads",
        "豆子清单已复制": "Bead List Copied",
        "豆绘小栈": "DouPin",
        "豆绘小栈图纸": "DouPin Pattern",
        "豆绘小栈图纸.pdf": "DouPin Pattern.pdf",
        "跟随系统": "Follow System",
        "转换中…": "Converting…",
        "转换参数": "Convert Options",
        "转换预览": "Convert Preview",
        "辅助线": "Guides",
        "输入标签": "Enter Tag",
        "边长": "Side",
        "返回数据无法解析": "Cannot Parse Response",
        "还有 {0} 种缺口，点「复制清单」查看全部": "{0} more colors short; tap Copy List to see all",
        "还没录入库存，去「库存」Tab 添加": "No stock yet — add it in the Stock tab",
        "还没有图纸": "No Patterns Yet",
        "还没有图纸用量数据": "No Usage Data Yet",
        "还没有图纸，先去创建": "No patterns yet, create one first",
        "还没有完成的作品": "No Finished Works Yet",
        "还没有库存数据": "No Stock Data Yet",
        "还没有库存数据，去「库存」Tab 录入": "No stock data yet — add it in the Stock tab",
        "还没有扫描结果": "No Scan Results Yet",
        "还没有文件夹": "No Folders Yet",
        "还没有文件夹，可到「图纸 → 文件夹」新建": "No folders yet — create one in Patterns → Folders",
        "还没有标签": "No Tags Yet",
        "远端最新提交 {0}（本包未注入构建号，无法精确对比）": "Latest remote commit {0} (no build ID in this package)",
        "连上后可直接回到图纸页点「开始拼豆」发送完整图或分色点亮。": "Then go back and tap Start Beading to send the full image or a single color.",
        "连接": "Connect",
        "连接与灯板": "Connection & Board",
        "连接中 {0}…": "Connecting to {0}…",
        "连接中…": "Connecting…",
        "连接拼豆板": "Connect Bead Board",
        "连接超时": "Connection Timed Out",
        "退出原图对比": "Exit Compare",
        "选 2 张以上图纸开始合并": "Select 2+ patterns to merge",
        "选一种颜色，灯板只亮这种颜色的位置": "Pick a color; the board lights only that color",
        "选择图片": "Choose Photo",
        "选择图纸": "Choose Pattern",
        "选择新色号": "Choose New Color",
        "逐条添加": "Add One by One",
        "逐格打卡模式（点击格子标记已拼）": "Cell mark mode (tap a cell to mark placed)",
        "逐行打卡": "By Row",
        "郁金香": "Tulip",
        "重叠行（对齐用）": "Overlap Rows (Align)",
        "重命名": "Rename",
        "重命名后，该仓内所有色号记录一并更新。": "All entries in this bin will be renamed too.",
        "重命名文件夹": "Rename Folder",
        "重命名豆仓": "Rename Bin",
        "重新选择": "Choose Again",
        "钥匙": "Key",
        "钱包": "Wallet",
        "链接格式无法解析，请重新复制分享链接。": "Cannot parse link; copy the share link again.",
        "镜像": "Mirror",
        "长按图片可存储到相册，或点右上角分享": "Long-press to save to Photos, or share from top right",
        "长按拖动排序为 P2（暂未实现，见 TODO）。": "Drag to reorder (P2, not implemented yet).",
        "闹钟": "Alarm",
        "阈值": "Threshold",
        "阈值越大合并越狠（0 = 不合并）。": "Higher threshold merges more (0 = no merge).",
        "附近设备": "Nearby Devices",
        "雨伞": "Umbrella",
        "雪人": "Snowman",
        "需{0} · 有{1}": "Need {0} · Have {1}",
        "音符": "Music Note",
        "项目仓库": "Project Repo",
        "预览": "Preview",
        "预览（像素化后）": "Preview (Pixelated)",
        "预计拆分为": "Estimated Split",
        "颜色": "Color",
        "颜色数量": "Color Count",
        "食物甜点": "Food & Dessert",
        "首次连接需要几秒": "First Connect Takes a Few Seconds",
        "首页": "Home",
        "高亮": "Highlight",
        "高亮中，点此取消": "Highlighted, Tap to Clear",
        "高亮模式": "Highlight Mode",
        "默认严格切分（重叠 0）。图纸 {0}×{1} 格。": "Strict split by default (overlap 0). Pattern {0}×{1} cells.",
        "默认亮度": "Default Brightness",
        "默认仓": "Default Bin",
        "默认只显示 PIXDOU / iLEDColor / Wofan 前缀或带 A950 服务的设备。": "Shows devices named PIXDOU / iLEDColor / Wofan or advertising A950.",
        "默认板尺寸与图纸一致。小图也可放到大板上指定位置。": "Board matches the pattern by default; small patterns can be placed on a bigger board.",
    ]

    /// 已解析的实际界面语言（system → 跟随系统首选语言）
    static var resolved: AppLanguage {
        switch current {
        case .system:
            let pref = Locale.preferredLanguages.first ?? "zh-Hans"
            return pref.hasPrefix("zh") ? .zh : .en
        default:
            return current
        }
    }

    /// 查表翻译（无插值文案）：中文界面原样返回，英文界面查表，缺失则回落中文
    static func s(_ zh: String) -> String {
        guard resolved == .en else { return zh }
        return enTable[zh] ?? zh
    }

    /// 同上，但返回 `LocalizedStringKey`（Section / ContentUnavailableView 等首参数需要）
    static func k(_ zh: String) -> LocalizedStringKey {
        LocalizedStringKey(s(zh))
    }

    /// 模板翻译的 `LocalizedStringKey` 版本
    static func pk(_ template: String, _ args: String...) -> LocalizedStringKey {
        LocalizedStringKey(p(template, args))
    }

    /// 变参重载（便于 `L10n.p("...", a, b)` 直接调用）
    static func p(_ template: String, _ args: String...) -> String {
        p(template, Array(args))
    }

    /// 模板翻译（含 {0}/{1} 占位符）：先按语言取模板，再依次填入参数
    static func p(_ template: String, _ args: [String]) -> String {
        var out = (resolved == .en ? (enTable[template] ?? template) : template)
        for (i, a) in args.enumerated() {
            out = out.replacingOccurrences(of: "{\(i)}", with: a)
        }
        return out
    }
}
