import Foundation

/// 内置图纸模板（原创像素图案）
struct PatternTemplate: Identifiable {
    let id = UUID()
    let name: String
    let category: String
    /// 字符 → 官方 colorId（0 = 空格）
    static let charMap: [Character: Int] = [
        "W": 185,  // 白 H2
        "K": 199,  // 黑 H16
        "G": 187,  // 灰 H4
        "L": 194,  // 浅灰 H11
        "R": 250,  // 红 R1
        "D": 144,  // 深红 F7
        "P": 125,  // 粉 E12
        "H": 118,  // 玫粉 E5
        "Y": 8,    // 黄 A8
        "A": 26,   // 金 A26
        "O": 252,  // 橙 R3
        "S": 127,  // 肤色 E14
        "B": 147,  // 棕 F10
        "g": 34,   // 绿 B8
        "l": 29,   // 浅绿 B3
        "d": 38,   // 深绿 B12
        "c": 82,   // 浅蓝 C24
        "b": 257,  // 蓝 R8
        "n": 70,   // 藏青 C12
        "V": 92,   // 紫 D5
        "v": 96,   // 浅紫 D9
        "M": 2,    // 米色 A2
        "C": 69,   // 青 C11
        "m": 263,  // 薄荷 R14
    ]

    var rows: [String]

    var width: Int { rows.map { $0.count }.max() ?? 0 }
    var height: Int { rows.count }

    /// 转为色号网格（colorId，0 = 空）
    var cells: [Int] {
        let w = width
        var out = [Int](repeating: 0, count: w * rows.count)
        for (y, row) in rows.enumerated() {
            for (x, ch) in row.enumerated() {
                out[y * w + x] = PatternTemplate.charMap[ch] ?? 0
            }
        }
        return out
    }
}

enum TemplateLibrary {
    static let all: [PatternTemplate] = [
        PatternTemplate(name: L10n.s("爱心"), category: L10n.s("爱心系"), rows: [
            "................",
            "..RRRR....RRRR..",
            ".RRRRRR..RRRRRR.",
            "RRRRRRRRRRRRRRRR",
            "RRRRRRRRRRRRRRRR",
            "RRRRRRRRRRRRRRRR",
            ".RRRRRRRRRRRRRR.",
            "..RRRRRRRRRRRR..",
            "...RRRRRRRRRR...",
            "....RRRRRRRR....",
            ".....RRRRRR.....",
            "......RRRR......",
            ".......RR.......",
            "................",
        ]),
        PatternTemplate(name: L10n.s("笑脸"), category: L10n.s("表情包"), rows: [
            "....YYYYYYYY....",
            "..YYYYYYYYYYYY..",
            ".YYYYYYYYYYYYYY.",
            ".YKKYYYYYYYYKKY.",
            ".YKKYYYYYYYYKKY.",
            "YYYYYYYYYYYYYYYY",
            "YYYYYYYYYYYYYYYY",
            "YYKYYYYYYYYYYKYY",
            "YYKKYYYYYYYYKKYY",
            "YYYKKKKKKKKKKYYY",
            ".YYYKKKKKKKKYYY.",
            "..YYYYYYYYYYYY..",
            "....YYYYYYYY....",
            "................",
        ]),
        PatternTemplate(name: L10n.s("五角星"), category: L10n.s("日常物件"), rows: [
            ".......AA.......",
            ".......AA.......",
            "......AAAA......",
            "......AAAA......",
            ".AAAAAAYYAAAAAA.",
            "AAAAAAAAAAAAAAAA",
            ".AAAAAAAAAAAAAA.",
            "..AAAAAAAAAAAA..",
            "...AAAAAAAAAA...",
            "...AAAAAAAAAA...",
            "..AAAAA..AAAAA..",
            "..AAA......AAA..",
            ".AAA........AAA.",
            ".AA..........AA.",
            "AA............AA",
            "................",
        ]),
        PatternTemplate(name: L10n.s("西瓜"), category: L10n.s("食物甜点"), rows: [
            "....gggggggg....",
            "..ggllllllllgg..",
            ".gllRRRRRRRRllg.",
            ".glRRRRRRRRRRlg.",
            "gllRRRKRRKRRRllg",
            "gllRRKKRRKKRRllg",
            "gllRRRRRRRRRRllg",
            ".glRRRRRRRRRRlg.",
            ".gllRRRRRRRRllg.",
            "..ggllllllllgg..",
            "....gggggggg....",
            "......gggg......",
            ".......gg.......",
            "................",
        ]),
        PatternTemplate(name: L10n.s("蘑菇"), category: L10n.s("植物花语"), rows: [
            ".....RRRRRR.....",
            "...RRWWRRRRRR...",
            "..RRRWWRRRRRRR..",
            ".RRRRRRWWRRRRRR.",
            "RRWRRRRRRWWRRRRR",
            "RRWWRRRRRRWWRRRR",
            "RRRRRRRRRRRRRRRR",
            ".RRRRRRRRRRRRRR.",
            "..MMMMMMMMMMMM..",
            "...MMMMMMMMMM...",
            "...MMMMMMMMMM...",
            "....MMMMMMMM....",
            "....MMMMMMMM....",
            "....MMMMMMMM....",
            "................",
        ]),
        PatternTemplate(name: L10n.s("小猫"), category: L10n.s("像素小动物"), rows: [
            "..KKK......KKK..",
            "..KWK......KWK..",
            "..KKK......KKK..",
            "..KKKKKKKKKKKK..",
            ".KKKKKKKKKKKKKK.",
            "KKWWKKKKKKKKWWKK",
            "KKWKKKKKKKKKKWKK",
            "KKKYYKKKKKKYYKKK",
            "KKKKKKKKKKKKKKKK",
            ".KKKWWKWWKWWKKK.",
            ".KKKKKKKKKKKKKK.",
            "..KKKKKKKKKKKK..",
            "...KKKK..KKKK...",
            "...KKK....KKK...",
            "...KKK....KKK...",
            "................",
        ]),
        PatternTemplate(name: L10n.s("兔子"), category: L10n.s("像素小动物"), rows: [
            "...WW......WW...",
            "..WWWW....WWWW..",
            "..WKKW....WKKW..",
            "..WWWW....WWWW..",
            "..WWWWWWWWWWWW..",
            ".WWWWWWWWWWWWWW.",
            ".WWKKWWWWWWKKWW.",
            "WWWWWWWWWWWWWWWW",
            "WWWPWWWWWWWKPWWW",
            "WWWKKWWWWWWKKWWW",
            "WWWWWWPPWWWWWWWW",
            ".WWWWWWWWWWWWWW.",
            ".WWWWWWWWWWWWWW.",
            "..WWWWWWWWWWWW..",
            "...WWWWWWWWWW...",
            ".....WWWWWW.....",
        ]),
        PatternTemplate(name: L10n.s("冰淇淋"), category: L10n.s("食物甜点"), rows: [
            "......PPPP......",
            ".....PPPPPP.....",
            "....PPPPPPPP....",
            "....PPMPPMPP....",
            "...PPPPPPPPPP...",
            "...PPMPPPPMPP...",
            "..PPPPPPPPPPPP..",
            "..PPPPMMPPPPPP..",
            ".PPPPPPPPPPPPPP.",
            ".PPPPPPPPPPPPP..",
            "PPPPPPPPPPPPPP..",
            ".PPPPPPPPPPPP...",
            "..BBBBBBBBBB....",
            "...BBBBBBBB.....",
            "....BBBBBB......",
            ".....BBBB.......",
        ]),
        PatternTemplate(name: L10n.s("蝴蝶结"), category: L10n.s("日常物件"), rows: [
            "....HH....HH....",
            "..HHHHH.HHHHH...",
            ".HHPPHHHHHPPHH..",
            ".HHPHHHHHHHHPHH.",
            "..HHPPHHHPPHH...",
            "..HHHHHHHHHHHH..",
            "..HHHHHHHHHHHH..",
            "..HHPPHHHPPHH...",
            ".HHPHHHHHHHHPHH.",
            ".HHPPHHHHHPPHH..",
            "..HHHHH.HHHHH...",
            "....HH....HH....",
            "................",
        ]),
        PatternTemplate(name: L10n.s("月亮"), category: L10n.s("太空星球"), rows: [
            "......YYYY......",
            "....YYYYYY......",
            "...YYYYY........",
            "..YYYY..........",
            "..YYYY..........",
            ".YYYY...........",
            ".YYYY...........",
            ".YYYY...........",
            "..YYYY..........",
            "..YYYY..........",
            "...YYYYY........",
            "....YYYYYY.Y....",
            "......YYYY.YY...",
            "...........Y....",
            "................",
            "................",
        ]),
        PatternTemplate(name: L10n.s("音符"), category: L10n.s("日常物件"), rows: [
            ".....KKKKKKK....",
            ".....KKKKKKKK...",
            ".....KKKKKKKK...",
            ".....KKKKKKK....",
            ".....KKKKK......",
            ".....KKK........",
            ".....KKK........",
            ".....KKK........",
            "..K..KKK........",
            ".KKK.KKK........",
            ".KKKKKK.........",
            "..KKKKK.........",
            "...KKK..........",
            "................",
        ]),
        PatternTemplate(name: L10n.s("圣诞树"), category: L10n.s("节日"), rows: [
            ".......dd.......",
            "......dddd......",
            ".....dddddd.....",
            "....dddddddd....",
            "...dddddddddd...",
            "..dddddddddddd..",
            ".dddddddddddddd.",
            "..dddddddddddd..",
            "...gggggggggg...",
            "....gggggggg....",
            ".....gggggg.....",
            "......gggg......",
            "......gggg......",
            "....BBBBBBBB....",
            "................",
        ]),
        PatternTemplate(name: L10n.s("南瓜"), category: L10n.s("节日"), rows: [
            ".....gggggg.....",
            "......gggg......",
            "....OOOOOOOO....",
            "...OOOOOOOOOO...",
            "..OOOOOOOOOOOO..",
            ".OAOOOOOOOOOOAO.",
            ".OAOOOOOOOOOOAO.",
            "OAOOOOOOOOOOOOAO",
            "OAOOOOOOOOOOOOAO",
            ".OAOOOOOOOOOOAO.",
            ".OOOOOOOOOOOOOO.",
            "..OOOOOOOOOOOO..",
            "...OOOOOOOOOO...",
            "....OOOOOOOO....",
            "................",
        ]),
        PatternTemplate(name: L10n.s("彩虹"), category: L10n.s("自然风景"), rows: [
            ".....RRRRRR.....",
            "...RRRRRRRRRR...",
            "..RRRRRRRRRRRR..",
            ".RRRR......RRRR.",
            ".RRR........RRR.",
            "AAAA......AAAA..",
            ".AAA........AAA.",
            "YYYY........YYYY",
            "YYYY........YYYY",
            "cccc........cccc",
            ".ccc........ccc.",
            "cccc........cccc",
            "bbbb........bbbb",
            ".bbb........bbb.",
            "................",
        ]),

        // ===== T05 扩充：套装分组（全部使用既有 charMap 字符，行长严格等长） =====

        // ----- 像素小动物 -----
        PatternTemplate(name: L10n.s("熊猫"), category: L10n.s("像素小动物"), rows: [
            "....KKKKKKKK....",
            "..KKWWWWWWWWKK..",
            ".KKWWWWWWWWWWKK.",
            ".KWWKKWWWWKKWWK.",
            ".KWWKKWWWWKKWWK.",
            ".KWWWWWWWWWWWWK.",
            "KKWWWWWKKWWWWWKK",
            "KKWWWWKKKKWWWWKK",
            ".KWWWWWWWWWWWWK.",
            ".KWWWWWWWWWWWWK.",
            ".KKWWWWWWWWWWKK.",
            "..KKWWWWWWWWKK..",
            "....KKWWWWKK....",
            "....KK....KK....",
            "................",
            "................",
        ]),
        PatternTemplate(name: L10n.s("小狗"), category: L10n.s("像素小动物"), rows: [
            "..BB........BB..",
            ".BBBB......BBBB.",
            ".BBBBBBBBBBBBBB.",
            ".BWWWWWWWWWWWWB.",
            ".BWKKWWWWWWKKWB.",
            "BBWWWWWWWWWWWWBB",
            "BBWWWWWWWWWWWWBB",
            ".BWWWWWKKWWWWWB.",
            ".BWWWWKKKKWWWWB.",
            ".BWWWWWKKWWWWWB.",
            "..BWWWWWWWWWWB..",
            "..BBWWWWWWWWBB..",
            "...BBBBBBBBBB...",
            "....BBBBBBBB....",
            "....BB....BB....",
            "....BB....BB....",
        ]),
        PatternTemplate(name: L10n.s("小牛"), category: L10n.s("像素小动物"), rows: [
            "...KK......KK...",
            "..KKKK....KKKK..",
            "..KWWKK..KKWWK..",
            "..KWWKKKKKKWWK..",
            "..KWWWWWWWWWWK..",
            ".KKWWWWWWWWWWKK.",
            ".KWWKKWWWWKKWWK.",
            ".KWWKKWWWWKKWWK.",
            ".KWWWWPPPPWWWWK.",
            ".KWWWWWWWWWWWWK.",
            "..KWWWWWWWWWWK..",
            "...KWWWWWWWWK...",
            "....KKKKKKKK....",
            "................",
        ]),
        PatternTemplate(name: L10n.s("小狐狸"), category: L10n.s("像素小动物"), rows: [
            "..OO........OO..",
            ".OOOO......OOOO.",
            ".OWWO......OWWO.",
            ".OWWO......OWWO.",
            "..OWWO....OWWO..",
            "..OWWWOOOOWWWO..",
            ".OWWWWWWWWWWWWO.",
            ".OWKKWWWWWWKKWO.",
            ".OWWWWWWWWWWWWO.",
            "..OWWWWWWWWWWO..",
            "...OWWKKKKWWO...",
            "...OWWWWWWWWO...",
            "....OWWWWWWO....",
            ".....OWWWWO.....",
            "......OWWO......",
            "................",
        ]),
        PatternTemplate(name: L10n.s("小鸡"), category: L10n.s("像素小动物"), rows: [
            "......YYYY......",
            ".....YYYYYY.....",
            "....YYYYYYYY....",
            "...YYKKYYKKYY...",
            "...YYKKYYKKYY...",
            "...YYYYYYYYYY...",
            "...YYYOOOOYYY...",
            "...YYYYYYYYYY...",
            "..YYYYYYYYYYYY..",
            ".YYYYYYYYYYYYYY.",
            ".YYYYYYYYYYYYYY.",
            "..YYYYYYYYYYYY..",
            "...YYYYYYYYYY...",
            "....YY....YY....",
            "....OO....OO....",
            "................",
        ]),
        PatternTemplate(name: L10n.s("小企鹅"), category: L10n.s("像素小动物"), rows: [
            ".....KKKKKK.....",
            "....KKKKKKKK....",
            "...KKWWWWWWKK...",
            "...KWWKKKKWWK...",
            "...KWWKKKKWWK...",
            "...KWWWWWWWWK...",
            "...KWWWOOOWWK...",
            "...KWWOOOOWWK...",
            "..KKWWWOOOWWWKK.",
            "..KWWWWWWWWWWWK.",
            "..KWWWWWWWWWWWK.",
            "..KKWWWWWWWWWKK.",
            "...KKWWWWWWWKK..",
            "....OOOOOOOO....",
            ".....OO..OO.....",
            "................",
        ]),

        // ----- 表情包 -----
        PatternTemplate(name: L10n.s("大笑"), category: L10n.s("表情包"), rows: [
            "....YYYYYYYY....",
            "..YYYYYYYYYYYY..",
            ".YYYYYYYYYYYYYY.",
            ".YYKKYYYYYYKKYY.",
            ".YYKKYYYYYYKKYY.",
            "YYYYYYYYYYYYYYYY",
            "YYYYYYYYYYYYYYYY",
            "YYKKKKKKKKKKKKYY",
            "YYKYYYKKKKYYYKYY",
            "YYKYYYYKKYYYYKYY",
            ".YYKKKKKKKKKKYY.",
            "..YYYYYYYYYYYY..",
            "....YYYYYYYY....",
            "................",
        ]),
        PatternTemplate(name: L10n.s("哭泣"), category: L10n.s("表情包"), rows: [
            "....YYYYYYYY....",
            "..YYYYYYYYYYYY..",
            ".YYYYYYYYYYYYYY.",
            ".YYKKYYYYYYKKYY.",
            ".YYKKYYYYYYKKYY.",
            "YYccYYYYYYYYccYY",
            "YYcccYYYYYYcccYY",
            "YYYcYYYYYYYYcYYY",
            "YYYcYKKKKKKYcYYY",
            "YYYcYYYYYYYYcYYY",
            ".YYcYYYYYYYYcYY.",
            "..YYccccccccYY..",
            "....YYYYYYYY....",
            "................",
        ]),
        PatternTemplate(name: L10n.s("爱心眼"), category: L10n.s("表情包"), rows: [
            "....YYYYYYYY....",
            "..YYYYYYYYYYYY..",
            ".YYYYYYYYYYYYYY.",
            ".YRRRYYYYYYRRRY.",
            ".RRRRRYYYYRRRRRY",
            ".RRRRRYYYYRRRRRY",
            ".YRRRYYYYYYRRRY.",
            "YYYYYYYYYYYYYYYY",
            "YYKYYYYYYYYYYKYY",
            "YYKKYYYYYYYYKKYY",
            ".YYKKKKKKKKKKYY.",
            "..YYYYYYYYYYYY..",
            "....YYYYYYYY....",
            "................",
        ]),
        PatternTemplate(name: "wink", category: L10n.s("表情包"), rows: [
            "....YYYYYYYY....",
            "..YYYYYYYYYYYY..",
            ".YYYYYYYYYYYYYY.",
            ".YYKKYYYYYYKKYY.",
            ".YYYYYYYYYYKKYY.",
            "YYYYYYYYYYYYYYYY",
            "YYYYYYYYYYYYYYYY",
            "YYKYYYYYYYYYYKYY",
            "YYKKYYYYYYYYKKYY",
            ".YYKKKKKKKKKKYY.",
            "..YYKKKKKKKKYY..",
            "..YYYYYYYYYYYY..",
            "....YYYYYYYY....",
            "................",
        ]),
        PatternTemplate(name: L10n.s("无语"), category: L10n.s("表情包"), rows: [
            "....YYYYYYYY....",
            "..YYYYYYYYYYYY..",
            ".YYYYYYYYYYYYYY.",
            ".YYYYYYYYYYYYYY.",
            ".YYKKYYYYYYKKYY.",
            ".YYKKYYYYYYKKYY.",
            "YYYYYYYYYYYYYYYY",
            "YYYYYYYYYYYYYYYY",
            "YYKKKKKKKKKKKKYY",
            "YYKKKKKKKKKKKKYY",
            ".YYYYYYYYYYYYYY.",
            "..YYYYYYYYYYYY..",
            "....YYYYYYYY....",
            "................",
        ]),

        // ----- 自然风景 -----
        PatternTemplate(name: L10n.s("太阳"), category: L10n.s("自然风景"), rows: [
            "..Y..YYYYYY..Y..",
            "...YYYYYYYYYY...",
            "..YYYYYYYYYYYY..",
            ".YYYYYYYYYYYYYY.",
            "YYYYYOOOOOOYYYYY",
            "YYYYOOAAAAOOYYYY",
            "YYYYOOAAAAOOYYYY",
            "YYYYYOOOOOOYYYYY",
            ".YYYYYYYYYYYYYY.",
            "..YYYYYYYYYYYY..",
            "...YYYYYYYYYY...",
            "..Y..YYYYYY..Y..",
            "................",
            "................",
        ]),
        PatternTemplate(name: L10n.s("云朵"), category: L10n.s("自然风景"), rows: [
            "......WWWW......",
            "....WWWWWWWW....",
            "...WWWWWWWWWW...",
            "..WWWWWWWWWWWW..",
            ".WWWWWWWWWWWWWW.",
            "WWWWWWWWWWWWWWWW",
            "WWWWWWWWWWWWWWWW",
            "WWWWWWWWWWWWWWWW",
            ".WWWWWWWWWWWWWW.",
            "..WWWWWWWWWWWW..",
            "....WWWWWWWW....",
            "................",
            "................",
            "................",
        ]),
        PatternTemplate(name: L10n.s("山峰"), category: L10n.s("自然风景"), rows: [
            ".......WW.......",
            "......WWWW......",
            ".....WWWWWW.....",
            "....WWWWWWWW....",
            "...WWWWWWWWWW...",
            "..WWWWdddWWWWW..",
            "...WWdgggdWWW...",
            "..WWWddggddWWW..",
            ".WWWWWWddWWWWWW.",
            "WWWWWWWWWWWWWWWW",
            "WWWWWWWWWWWWWWWW",
            "dddddddddddddddd",
            "dddddddddddddddd",
            "................",
        ]),
        PatternTemplate(name: L10n.s("海浪"), category: L10n.s("自然风景"), rows: [
            "................",
            "..cccc..cccc....",
            ".cccccc.cccccc..",
            "cccccccccccccccc",
            "cccccccccccccccc",
            "cccccccccccccccc",
            ".bbbbbbbbbbbbbb.",
            "bbbbbbbbbbbbbbbb",
            "bbbbbbbbbbbbbbbb",
            ".nnnnnnnnnnnnnn.",
            "nnnnnnnnnnnnnnnn",
            "nnnnnnnnnnnnnnnn",
            "................",
            "................",
        ]),
        PatternTemplate(name: L10n.s("向日葵"), category: L10n.s("自然风景"), rows: [
            "..Y...OOOO...Y..",
            "...Y.OOOOOO.Y...",
            "..Y.OOAOOAOO.Y..",
            "....OOAAOAAOO...",
            ".Y.OOOOOOOOOO.Y.",
            "..YOOAAOAAOOOY..",
            ".Y.OOOOOOOOOO.Y.",
            "....OOAAOAAOO...",
            "..Y.OOAOOAOO.Y..",
            "...Y.OOOOOO.Y...",
            "..Y...OOOO...Y..",
            "..d...YggY...d..",
            "......gggg......",
            "......gggg......",
            ".....dddddd.....",
            "................",
        ]),

        // ----- 节日 -----
        PatternTemplate(name: L10n.s("圣诞袜"), category: L10n.s("节日"), rows: [
            "..RRRR..RRRRRR..",
            ".RRRRRR.RRRRRRR.",
            ".RWWWWR.RWWWWWR.",
            ".RRRRRR.RRRRRRR.",
            "..RRRR..RRRRRR..",
            "......RRRRRRRR..",
            "......RRRRRRRR..",
            "......RRRRRRRR..",
            "......RRRRRRRR..",
            ".....RRRRRRRRR..",
            ".....RRRRRRRR...",
            "....WRRRRRRR....",
            "....WRRRRRR.....",
            "....WWRRRR......",
            ".....WWWW.......",
            "................",
        ]),
        PatternTemplate(name: L10n.s("雪人"), category: L10n.s("节日"), rows: [
            "......WWWW......",
            ".....WWWWWW.....",
            "....WWKKKKWW....",
            "....WWKKKKWW....",
            "....WWWOOOWW....",
            ".....WWWWWW.....",
            "......WWWW......",
            "....WWWWWWWW....",
            "...WWWWWWWWWW...",
            "...WWRWWWWRWW...",
            "...WWWWWWWWWW...",
            "...WWRWWWWRWW...",
            "....WWWWWWWW....",
            "....WWWWWWWW....",
            ".....WWWWWW.....",
            "................",
        ]),
        PatternTemplate(name: L10n.s("礼物盒"), category: L10n.s("节日"), rows: [
            "....Y..YY..Y....",
            "...YY..YY..YY...",
            "..YYY.YYYY.YYY..",
            "..YY..YYYY..YY..",
            "...YY.YYYY.YY...",
            "RRRRRRYYYYRRRRRR",
            "RRRRRRYYYYRRRRRR",
            "RRRRRYRRRRYRRRRR",
            "RRRRRYRRRRYRRRRR",
            "RRRRRYRRRRYRRRRR",
            "RRRRRYRRRRYRRRRR",
            "RRRRRRYYYYRRRRRR",
            "RRRRRRYYYYRRRRRR",
            "RRRRRRYYYYRRRRRR",
            "................",
            "................",
        ]),
        PatternTemplate(name: L10n.s("生日蛋糕"), category: L10n.s("节日"), rows: [
            "....Y...Y...Y...",
            "...YYY.YYY.YYY..",
            "...Y.Y.Y.Y.Y.Y..",
            "....Y...Y...Y...",
            "..PPPPPPPPPPPP..",
            ".PPPPPPPPPPPPPP.",
            ".PWWPWWPWWPWWPP.",
            ".PPPPPPPPPPPPPP.",
            "RRRRRRRRRRRRRRRR",
            "RWWWRWWWRWWWRWWR",
            "RRRRRRRRRRRRRRRR",
            "YYYYYYYYYYYYYYYY",
            "YYYYYYYYYYYYYYYY",
            "................",
        ]),
        PatternTemplate(name: L10n.s("新年灯笼"), category: L10n.s("节日"), rows: [
            "......AAAA......",
            "......AAAA......",
            "....AAAAAAAA....",
            "..RRRRRRRRRRRR..",
            ".RRRRRRRRRRRRRR.",
            ".RYRRRRRRRRRRYR.",
            ".RRRRRRRRRRRRRR.",
            ".RRRRRRRRRRRRRR.",
            ".RYRRRRRRRRRRYR.",
            ".RRRRRRRRRRRRRR.",
            "..RRRRRRRRRRRR..",
            "....AAAAAAAA....",
            "......AAAA......",
            "....AAAAAAAA....",
            "................",
        ]),

        // ----- 食物甜点 -----
        PatternTemplate(name: L10n.s("甜甜圈"), category: L10n.s("食物甜点"), rows: [
            "..HHHHHHHHHHHH..",
            ".HHHHHHHHHHHHHH.",
            "HHPPHHPHHPPHHPHH",
            "HPHPPPPPPPPPPHPH",
            "HHPPPP....PPPPHH",
            "HPPPPP....PPPPPH",
            "HPPPPP....PPPPPH",
            "HHPPPP....PPPPHH",
            "HPHPPPPPPPPPPHPH",
            "HHPPHHPHHPPHHPHH",
            ".HHHHHHHHHHHHHH.",
            "..HHHHHHHHHHHH..",
            "................",
            "................",
        ]),
        PatternTemplate(name: L10n.s("棒棒糖"), category: L10n.s("食物甜点"), rows: [
            "....RRRRRRRR....",
            "..RRPPPPPPPPRR..",
            ".RPPPPPPPPPPPPR.",
            ".RPPWWPPWWPPWPR.",
            "RPPWWPPWWPPWWPPR",
            "RPPPPPPWWPPPPPPR",
            "RPPWWPPWWPPWWPPR",
            "RPPWWPPWWPPWWPPR",
            "RPPPPPPWWPPPPPPR",
            ".RPPWWPPWWPPWPR.",
            ".RPPPPPPPPPPPPR.",
            "..RRPPPPPPPPRR..",
            "....RRRRRRRR....",
            "......WW........",
            "......WW........",
            "......WW........",
        ]),
        PatternTemplate(name: L10n.s("草莓"), category: L10n.s("食物甜点"), rows: [
            "....gg..gg......",
            "....gggggg..dd..",
            "...gggggggg.dd..",
            "...gRRRRRRg.....",
            "..RRRRRRRRRR....",
            "..RWRRRRRRRR....",
            ".RRRRRRWRRRRR...",
            ".RRRRRRRRRRRR...",
            ".RRWRRRRRRRRR...",
            "..RRRRRRWRRR....",
            "..RRRRRRRRRR....",
            "...RRRRRRRR.....",
            "....RRRRRR......",
            ".....RRRR.......",
            "......RR........",
            "................",
        ]),
        PatternTemplate(name: L10n.s("咖啡杯"), category: L10n.s("食物甜点"), rows: [
            "..BBBBBBBBBBBB..",
            ".BWWWWWWWWWWWWB.",
            ".BWWWWWWWWWWWWB.",
            "BBBBBBBBBBBBBBBB",
            "BWKWWKWWKWWKWWKB",
            "BWWWWWWWWWWWWWWB",
            "BWWWWWWWWWWWWWWB",
            "BWWWWWWWWWWWWWWB",
            ".BWWWWWWWWWWWWB.",
            "..BBBBBBBBBBBB..",
            "..BB........BB..",
            "..BBBB....BBBB..",
            "...BBBBBBBBBB...",
            "................",
            "................",
        ]),
        PatternTemplate(name: L10n.s("纸杯蛋糕"), category: L10n.s("食物甜点"), rows: [
            "......RRRR......",
            "....RRRRRRRR....",
            "...RPPPPPPPPR...",
            "..PPWWPPWWPPWW..",
            "..PPPPPPPPPPPP..",
            ".PPWWPPWWPPWWPP.",
            ".PPPPPPPPPPPPPP.",
            "..BBBBBBBBBBBB..",
            "..BBBBBBBBBBBB..",
            "...BBBBBBBBBB...",
            "...BBBBBBBBBB...",
            "....BBBBBBBB....",
            "....BBBBBBBB....",
            ".....BBBBBB.....",
            "................",
            "................",
        ]),
        PatternTemplate(name: L10n.s("寿司"), category: L10n.s("食物甜点"), rows: [
            "..WWWWWWWWWWWW..",
            ".WOOOOOOOOOOOOW.",
            ".WOOdddddddOOOW.",
            ".WOdddddddddOOW.",
            ".WOOdddddddOOOW.",
            ".WOOOOOOOOOOOOW.",
            "..WWWWWWWWWWWW..",
            ".KKKKKKKKKKKKKK.",
            ".KKGGGGGGGGGGKK.",
            ".KKGGGGGGGGGGKK.",
            ".KKGGGGGGGGGGKK.",
            ".KKKKKKKKKKKKKK.",
            "................",
            "................",
        ]),

        // ----- 字母数字 -----
        PatternTemplate(name: L10n.s("字母 A"), category: L10n.s("字母数字"), rows: [
            "......bbbb......",
            ".....bbbbbb.....",
            "....bb....bb....",
            "...bb......bb...",
            "...bb......bb...",
            "..bb........bb..",
            "..bbbbbbbbbbbb..",
            "..bbbbbbbbbbbb..",
            ".bb..........bb.",
            ".bb..........bb.",
            "bb............bb",
            "bb............bb",
            "................",
            "................",
        ]),
        PatternTemplate(name: L10n.s("字母 K"), category: L10n.s("字母数字"), rows: [
            "bb..........bb..",
            "bb........bb....",
            "bb......bb......",
            "bb....bb........",
            "bb..bb..........",
            "bbbb............",
            "bbbbbb..........",
            "bb..bb..........",
            "bb....bb........",
            "bb......bb......",
            "bb........bb....",
            "bb..........bb..",
            "................",
            "................",
        ]),
        PatternTemplate(name: L10n.s("数字 8"), category: L10n.s("字母数字"), rows: [
            "....VVVVVVVV....",
            "..VVVVVVVVVVVV..",
            ".VVVV......VVVV.",
            ".VVV........VVV.",
            ".VVVV......VVVV.",
            "..VVVVVVVVVVVV..",
            "..VVVVVVVVVVVV..",
            ".VVVV......VVVV.",
            ".VVV........VVV.",
            ".VVVV......VVVV.",
            "..VVVVVVVVVVVV..",
            "....VVVVVVVV....",
            "................",
            "................",
        ]),
        PatternTemplate(name: L10n.s("数字 0"), category: L10n.s("字母数字"), rows: [
            "....OOOOOOOO....",
            "..OOOOOOOOOOOO..",
            ".OOOO......OOOO.",
            "OOOO........OOOO",
            "OOOO........OOOO",
            "OOOO........OOOO",
            "OOOO........OOOO",
            "OOOO........OOOO",
            "OOOO........OOOO",
            ".OOOO......OOOO.",
            "..OOOOOOOOOOOO..",
            "....OOOOOOOO....",
            "................",
            "................",
        ]),

        // ----- 爱心系 -----
        PatternTemplate(name: L10n.s("双心"), category: L10n.s("爱心系"), rows: [
            "................",
            "..RRR....RRR....",
            ".RRRRR..RRRRR...",
            "RRRRRRRRRRRRRR..",
            "RRRRRRRRRRRRRR..",
            ".RRRRRRRRRRRR...",
            "..RRRRRRRRRR....",
            "...RRRRRRRR.....",
            "....RRRRRR......",
            ".....RRRR.......",
            "......RR........",
            "................",
            "................",
            "................",
        ]),
        PatternTemplate(name: L10n.s("粉色爱心"), category: L10n.s("爱心系"), rows: [
            "................",
            "..PPPP....PPPP..",
            ".PPPPPP..PPPPPP.",
            "PPPPPPPPPPPPPPPP",
            "PPPPPPPPPPPPPPPP",
            "PPPPPPPPPPPPPPPP",
            ".PPPPPPPPPPPPPP.",
            "..PPPPPPPPPPPP..",
            "...PPPPPPPPPP...",
            "....PPPPPPPP....",
            ".....PPPPPP.....",
            "......PPPP......",
            ".......PP.......",
            "................",
        ]),
        PatternTemplate(name: L10n.s("碎花爱心"), category: L10n.s("爱心系"), rows: [
            "................",
            "..RRRR....RRRR..",
            ".RWRWRR..RRWRWR.",
            "RRRRRRRRRRRRRRRR",
            "RWRRRWRRRWRRRWRR",
            "RRRRRRRRRRRRRRRR",
            ".RRWRRRRRRRRWRR.",
            "..RRRRWRRRRRRR..",
            "...RRRRRRWRRR...",
            "....RWRRRRRR....",
            ".....RRRRRR.....",
            "......RRRR......",
            ".......RR.......",
            "................",
        ]),

        // ----- 植物花语 -----
        PatternTemplate(name: L10n.s("郁金香"), category: L10n.s("植物花语"), rows: [
            "..V..VV..VV..V..",
            "..VVVVVVVVVVVV..",
            "..VVVVVVVVVVVV..",
            "..VVVVVVVVVVVV..",
            "...VVVVVVVVVV...",
            "....VVVVVVVV....",
            "......gggg......",
            "......gggg......",
            "...gg.gggg.gg...",
            "....gggggggg....",
            "......gggg......",
            "......gggg......",
            "......gggg......",
            "................",
        ]),
        PatternTemplate(name: L10n.s("樱花"), category: L10n.s("植物花语"), rows: [
            "......PPPP......",
            "..PPP.PPPP.PPP..",
            ".PPPPP.PP.PPPPP.",
            "PPPPPPPPPPPPPPPP",
            ".PPPPP.PP.PPPPP.",
            "..PPP.PPPP.PPP..",
            ".....PPPPPP.....",
            "....PP.YY.PP....",
            ".....PYWWYP.....",
            "......YYY.......",
            "......BB........",
            "......BB........",
            "....BBBBBB......",
            "......BB........",
            "................",
            "................",
        ]),
        PatternTemplate(name: L10n.s("仙人掌"), category: L10n.s("植物花语"), rows: [
            "......gggg......",
            "......gggg......",
            "..gg..gggg..gg..",
            "..gg..gggg..gg..",
            "..ggg.gggg.ggg..",
            "..gggggggggggg..",
            "..gggggggggggg..",
            "..gggggggggggg..",
            "......gggg......",
            "......gggg......",
            "......gggg......",
            "......gggg......",
            "....BBBBBBBB....",
            "...BBBBBBBBBB...",
            "................",
            "................",
        ]),
        PatternTemplate(name: L10n.s("枫叶"), category: L10n.s("植物花语"), rows: [
            "......BB........",
            "....BBBBBB......",
            "...BBDBBBBB.....",
            "..BBBBBBBBBB....",
            ".BB.BBBBBB.BB...",
            "..BBBBBBBBBB....",
            "...BBBBBBBB.....",
            "..BBBBBBBBBB....",
            ".BBB.BBBB.BBB...",
            "..BBBBBBBBBB....",
            "......BB........",
            "......BB........",
            ".....BBBB.......",
            "......BB........",
            "................",
        ]),

        // ----- 太空星球 -----
        PatternTemplate(name: L10n.s("土星"), category: L10n.s("太空星球"), rows: [
            "......CCCC......",
            "....CCnnnnCC....",
            "...CnnnnnnnnC...",
            "..CnnnnCCnnnnC..",
            ".AAAAAAAAAAAAAA.",
            "AAAACnnnnnnnnCAA",
            "..CnnnnnnnnnnC..",
            "..CnnnnnnnnnnC..",
            ".AAAAAAAAAAAAAA.",
            "A...CnnnnnnC...A",
            "AAA.CnnnnnnC.AAA",
            "..A.CnnnnnnC.A..",
            "....CCnnnnCC....",
            "......CCCC......",
            "................",
            "................",
        ]),
        PatternTemplate(name: L10n.s("月牙星"), category: L10n.s("太空星球"), rows: [
            "......YYYY......",
            "....YYYYYY......",
            "...YYYYY........",
            "..YYYY..........",
            "..YYYY......Y...",
            ".YYYY......YYY..",
            ".YYYY......YYYY.",
            ".YYYY.......YY..",
            "..YYYY.......Y..",
            "..YYYY..........",
            "...YYYYY....Y...",
            "....YYYYYY.YY...",
            "......YYYY.Y....",
            "................",
            "................",
            "................",
        ]),
        PatternTemplate(name: L10n.s("火箭"), category: L10n.s("太空星球"), rows: [
            ".......RR.......",
            "......RWRR......",
            ".....RRWWRR.....",
            "....RRRWWRRR....",
            "....RWccccR.....",
            "....RWccccR.....",
            "....RRWccWRR....",
            "....RRRRRRRR....",
            "...RR..RR..RR...",
            "..RR...RR...RR..",
            ".RR....RR....RR.",
            "RR.....RR.....RR",
            ".......RR.......",
            "......OOOO......",
            ".....OOYYOO.....",
            "......OOOO......",
        ]),
        PatternTemplate(name: L10n.s("星星点点"), category: L10n.s("太空星球"), rows: [
            ".Y....Y.....Y...",
            "YYY..YYY...YYY..",
            ".Y....Y.....Y...",
            "................",
            ".....Y....Y.....",
            "....YYY..YYY....",
            ".....Y....Y.....",
            "................",
            "..Y....Y.....Y..",
            ".YYY..YYY...YYY.",
            "..Y....Y.....Y..",
            "................",
            ".Y....Y....Y....",
            "YYY..YYY..YYY...",
            ".Y....Y....Y....",
            "................",
        ]),

        // ----- 日常物件 -----
        PatternTemplate(name: L10n.s("咖啡杯日常"), category: L10n.s("日常物件"), rows: [
            "..cccccccccccc..",
            ".cbbbbbbbbbbbc..",
            ".cbbbbbbbbbbbc..",
            "ccccccccccccccc.",
            "..cbbbbbbbbbc...",
            "..cbbbbbbbbbc...",
            "..cbbbbbbbbbc...",
            "..cbbbbbbbbbc...",
            "..cbbbbbbbbbc...",
            "...ccccccccc....",
            "....BBBBBBB.....",
            "....BBBBBBB.....",
            "....BBBBBBB.....",
            "................",
            "................",
            "................",
        ]),
        PatternTemplate(name: L10n.s("钱包"), category: L10n.s("日常物件"), rows: [
            "..BBBBBBBBBBBB..",
            ".BBBBBBBBBBBBBB.",
            "BBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBB",
            "BBBBBBBAAAAABBBB",
            "BBBBBBAAAAAAABBB",
            "BBBBBBBAAAAABBBB",
            "BBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBB",
            ".BBBBBBBBBBBBBB.",
            "..BBBBBBBBBBBB..",
            "................",
            "................",
            "................",
        ]),
        PatternTemplate(name: L10n.s("雨伞"), category: L10n.s("日常物件"), rows: [
            "......RRRR......",
            "....RRRRRRRR....",
            "...RRRRRRRRRR...",
            "..RRWRRRRRRWRR..",
            ".RRWRRRRRRRRWRR.",
            "RRRRRRRRRRRRRRRR",
            "RRWRRRRRRRRWRRRR",
            ".RRRRRRRRRRRRRR.",
            ".......BB.......",
            ".......BB.......",
            ".......BB.......",
            ".......BB.......",
            ".......BBBB.....",
            "........BBBB....",
            ".........BB.....",
            "................",
        ]),
        PatternTemplate(name: L10n.s("钥匙"), category: L10n.s("日常物件"), rows: [
            "....AAAA........",
            "...AA..AA.......",
            "..AA....AA......",
            "..AA....AA......",
            "..AA....AA......",
            "...AA..AA.......",
            "....AAAA..AA....",
            "......AA..AA....",
            "......AAAAAAAA..",
            "......AA..AA....",
            "......AAAAAA....",
            "......AA........",
            "......AAAAAAAA..",
            "......AA..AA....",
            "......AAAAAA....",
            "................",
        ]),
        PatternTemplate(name: L10n.s("闹钟"), category: L10n.s("日常物件"), rows: [
            ".RR..........RR.",
            "RRRR........RRRR",
            "..RR.RRRRRR.RR..",
            "....RRRRRRRR....",
            "..RRRRRRRRRRRR..",
            ".RRRRRRKRRRRRRR.",
            ".RRRRRRKRRRRRRR.",
            ".RRRRRRKKKKRRRR.",
            ".RRRRRRRRRRRRRR.",
            "..RRRRRRRRRRRR..",
            "....RRRRRRRR....",
            "..RR..RRRR..RR..",
            "RRRR........RRRR",
            ".RR..........RR.",
            "................",
            "................",
        ]),
    ]

    static var categories: [String] {
        Array(Set(all.map { $0.category })).sorted()
    }
}
